[aws]
symbol = "â˜ï¸  "

[buf]
symbol = "ğŸƒ "

[c]
symbol = "C "

[conda]
symbol = "ğŸ…’  "

[dart]
symbol = "ğŸ¯ "

[directory]
read_only = " ï ½"
truncation_length = 100
truncate_to_repo = false
style = "yellow"
format = "[$path]($style)[$read_only]($read_only_style) "

[username]
show_always = true
format = "[#](bold blue) [$user]($style) in "
style_user = "bold cyan"

[hostname]
ssh_only = false
trim_at = ""
ssh_symbol = ""
style = "bold green"

[docker_context]
symbol = "ğŸ³ "

[elixir]
symbol = "ğŸ’§ "

[elm]
symbol = "ğŸŒ³ "

[git_branch]
symbol = "î‚  "

[golang]
symbol = "ğŸ¹ "

[haskell]
symbol = "Î» "

[hg_branch]
symbol = "î‚  "

[java]
symbol = "â˜• "

[julia]
symbol = "à®ƒ "

[memory_usage]
symbol = "ğŸ "

[nim]
symbol = "ğŸ‘‘ "

[nix_shell]
symbol = "â„ï¸ "

[nodejs]
symbol = ""

[package]
symbol = "ğŸ“¦ "

[python]
symbol = "ğŸ "

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "ğŸ¦€ "